# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            Frédéric Bardolle
tagline:          'Entrepreneur public'
url:              http://seiteta.github.io
baseurl:          https://seiteta.github.io/

author:
  name:           'Frédéric Bardolle'
  url:            https://twitter.com/seiteta

paginate:         5
