# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
tagline:          'Entrepreneur public'

paginate:         5

#SEO tag
title:            Frédéric Bardolle
description:      Innovation publique, éthique & IA
url:              http://seiteta.github.io
author:
  name:           'Frédéric Bardolle'
  twitter:        seiteta
social:
  name: Frédéric Bardolle
  links:
    - https://twitter.com/seiteta
    - https://www.linkedin.com/in/fbardolle
lang: fr_FR

plugins:
  - jekyll-seo-tag
