# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Frédéric Bardolle
tagline:          'Entrepreneur public'
url:              http://seiteta.github.io
baseurl:          https://seiteta.github.io/

author:
  name:           'Frédéric Bardolle'
  url:            https://twitter.com/seiteta

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
